### PR TITLE
Custom enrichments

### PR DESCRIPTION
**Pull request by lucasdchamps**
Also contains the renaming changes. Only check out changes in the `concepts/nlp_lexic/entity.md` file

### CODE REVIEW

**Comment by janteuni** [comment]
@mackayl This documentation is for the Custom Entity Enrichment, for the January Release - (Jan 21)

**Comment by mackayl** [comment]
I edited entity.md and also included Lucas's feedback :-)

**Comment by mackayl** [comment]
@lucasdchamps @janteuni Gentle reminder about my question above (_There are two references to gazette in the "How restricted custom entities work" section. Can you please check whether one of them should be deleted?_)

If you don't mind, I'll leave it to you to merge this pull request. I edited entity.md as requested (and also included Lucas's feedback), but it looks like the pull request contains a lot of other stuff too.

Thanks!

**Comment by janteuni** [comment]
Hello @mackayl I've checked the "gazette" occurence, and we still have one now, but we need it.
For the final merge, I will do it, since yes you right, we have another PR that touch the same files :)

**Pull request merged**
